
all:
	protoc25 --java_out=../java/src/main/java/ SignalService.proto Provisioning.proto WebSocketResources.proto StickerResources.proto
	protoc25 --java_out=../java/src/main/java/ UnidentifiedDelivery.proto
	protoc25 --java_out=../java/src/main/java/ WhisperTextProtocol.proto LocalStorageProtocol.proto FingerprintProtocol.proto
