val signalBuildToolsVersion by extra("35.0.0")
val signalCompileSdkVersion by extra("android-35")
val signalTargetSdkVersion by extra(34)
val signalMinSdkVersion by extra(21)
val signalNdkVersion by extra("28.0.13004108")
val signalJavaVersion by extra(JavaVersion.VERSION_17)
val signalKotlinJvmTarget by extra("17")
