/*
 * Copyright 2026 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.signal.registration.screens.twofactorselection

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Serializable
import org.signal.registration.RegistrationRoute

/**
 * Two-factor authentication methods that may be presented on the two-factor selection screen. Which ones are actually
 * offered depends on what the account has registered.
 */
@Serializable
sealed interface TwoFactorMethod : Parcelable {

  /** A device biometric or FIDO2 passkey, along with what a ceremony against it needs. */
  @Serializable
  @Parcelize
  data class Passkey(val parameters: WebAuthnParameters) : TwoFactorMethod

  /** A one-time code generated by the user's authenticator app. */
  @Serializable
  @Parcelize
  data object AuthenticatorApp : TwoFactorMethod
}

/**
 * The route to send the user to in order to authenticate with one of these [TwoFactorMethod]s. An account with nothing
 * but authenticator apps has no choice to make, so we skip straight to the code entry screen. Anything involving a
 * passkey goes through the selection screen, which is where the passkey ceremony is started from.
 *
 * Multiple entries of a kind are fine: the service checks the credential against every one the account has registered.
 */
fun List<TwoFactorMethod>.toAuthenticationRoute(): RegistrationRoute {
  return if (isNotEmpty() && all { it is TwoFactorMethod.AuthenticatorApp }) {
    RegistrationRoute.TotpEntry
  } else {
    RegistrationRoute.TwoFactorSelection(methods = this)
  }
}
