/*
 * Copyright 2026 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.signal.registration.screens.twofactorselection

import org.signal.registration.RegistrationRoute

/**
 * Two-factor authentication methods that may be presented on the two-factor selection screen. Which ones are actually
 * offered depends on what the account has registered.
 */
enum class TwoFactorMethod {
  /** A device biometric or FIDO2 passkey. */
  Passkey,

  /** A one-time code generated by the user's authenticator app. */
  AuthenticatorApp
}

/**
 * The route to send the user to in order to authenticate with one of these [TwoFactorMethod]s. When they're all of the
 * same kind, the selection screen has nothing to choose between, so we skip straight to that method. Multiple entries
 * of a kind are fine: the service checks the credential against every one the account has registered.
 */
fun List<TwoFactorMethod>.toAuthenticationRoute(): RegistrationRoute {
  return when (toSet().singleOrNull()) {
    TwoFactorMethod.AuthenticatorApp -> RegistrationRoute.TotpEntry
    else -> RegistrationRoute.TwoFactorSelection(methods = this)
  }
}
