# Auto-generated - DO NOT EDIT!
# To regenerate, edit openssl.config, then run:
#     ./import_openssl.sh import /path/to/openssl-1.0.1h.tar.gz
#
openssl_cflags_64 := \
  -DOPENSSL_THREADS \
  -D_REENTRANT \
  -DDSO_DLFCN \
  -DHAVE_DLFCN_H \
  -DL_ENDIAN \
  -DTERMIO \
  -DOPENSSL_NO_CAMELLIA \
  -DOPENSSL_NO_CAPIENG \
  -DOPENSSL_NO_CAST \
  -DOPENSSL_NO_DTLS1 \
  -DOPENSSL_NO_EC_NISTP_64_GCC_128 \
  -DOPENSSL_NO_GMP \
  -DOPENSSL_NO_GOST \
  -DOPENSSL_NO_HEARTBEATS \
  -DOPENSSL_NO_IDEA \
  -DOPENSSL_NO_JPAKE \
  -DOPENSSL_NO_MD2 \
  -DOPENSSL_NO_MDC2 \
  -DOPENSSL_NO_RC5 \
  -DOPENSSL_NO_RDRAND \
  -DOPENSSL_NO_RFC3779 \
  -DOPENSSL_NO_RIPEMD \
  -DOPENSSL_NO_RSAX \
  -DOPENSSL_NO_SCTP \
  -DOPENSSL_NO_SEED \
  -DOPENSSL_NO_SHA0 \
  -DOPENSSL_NO_STATIC_ENGINE \
  -DOPENSSL_NO_STORE \
  -DOPENSSL_NO_WHIRLPOOL \

openssl_cflags_static_64 := \
  -DOPENSSL_THREADS \
  -D_REENTRANT \
  -DL_ENDIAN \
  -DTERMIO \
  -DOPENSSL_NO_CAMELLIA \
  -DOPENSSL_NO_CAPIENG \
  -DOPENSSL_NO_CAST \
  -DOPENSSL_NO_DTLS1 \
  -DOPENSSL_NO_EC_NISTP_64_GCC_128 \
  -DOPENSSL_NO_GMP \
  -DOPENSSL_NO_GOST \
  -DOPENSSL_NO_HEARTBEATS \
  -DOPENSSL_NO_IDEA \
  -DOPENSSL_NO_JPAKE \
  -DOPENSSL_NO_MD2 \
  -DOPENSSL_NO_MDC2 \
  -DOPENSSL_NO_RC5 \
  -DOPENSSL_NO_RDRAND \
  -DOPENSSL_NO_RFC3779 \
  -DOPENSSL_NO_RIPEMD \
  -DOPENSSL_NO_RSAX \
  -DOPENSSL_NO_SCTP \
  -DOPENSSL_NO_SEED \
  -DOPENSSL_NO_SHA0 \
  -DOPENSSL_NO_STATIC_ENGINE \
  -DOPENSSL_NO_STORE \
  -DOPENSSL_NO_WHIRLPOOL \

