import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val annotation: String = "1.1.0"

  const val appcompat: String = "1.1.0-beta01"

  const val androidx_camera: String = "1.0.0-alpha02"

  const val cardview: String = "1.0.0"

  const val constraintlayout: String = "1.1.3"

  const val exifinterface: String = "1.0.0"

  const val gridlayout: String = "1.0.0"

  const val androidx_legacy: String = "1.0.0"

  const val androidx_lifecycle: String = "2.0.0"

  const val multidex_instrumentation: String = "2.0.0"

  const val multidex: String = "2.0.1"

  const val preference: String = "1.0.0"

  const val recyclerview: String = "1.0.0"

  const val androidx_test_core: String = "1.2.0"

  const val numberpickerview: String = "1.0.9" // available: "1.2.0"

  const val com_amulyakhare_textdrawable: String = "1.0.1"

  const val aapt2: String = "3.3.2-5309881" // available: "3.5.0-5435860"

  const val com_android_tools_build_gradle: String = "3.3.2" // available: "3.5.0"

  const val lint_gradle: String = "26.3.2" // available: "26.5.0"

  const val stream: String = "1.1.8" // available: "1.2.1"

  const val stickyheadergrid: String = "0.9.4" // available: "0.9.7"

  const val subsampling_scale_image_view: String = "3.6.0" // available: "3.10.0"

  const val com_github_bumptech_glide: String = "4.9.0"

  const val photoview: String = "2.1.3"

  const val com_github_dmytrodanylyk_circular_progress_button_library: String = "1.1.3-S2"
       // available: "1.1.3"

  const val com_google_android_exoplayer: String = "2.9.1" // available: "2.10.4"

  const val play_services_auth: String = "16.0.1" // available: "17.0.0"

  const val play_services_location: String = "16.0.0" // available: "17.0.0"

  const val play_services_maps: String = "16.1.0" // available: "17.0.0"

  const val material: String = "1.0.0"

  const val com_google_dexmaker: String = "1.2"

  const val firebase_messaging: String = "17.3.4" // available: "20.0.0"

  const val android_integration: String = "3.1.0" // available: "3.3.0"

  const val com_google_zxing_core: String = "3.2.1" // available: "3.4.0"

  const val ez_vcard: String = "0.9.11"

  const val com_jpardogo_materialtabstrip_library: String = "1.0.9" // available: "1.1.1"

  const val android_smsmms: String = "4.0.1" // available: "5.1.4"

  const val roundedimageview: String = "2.1.0" // available: "2.1.1"

  const val floatingactionbutton: String = "1.3.0"

  const val materialish_progress: String = "1.5" // available: "1.7"

  const val assertj_android: String = "1.1.1" // available: "1.2.0"

  const val colorpicker: String = "0.9.1" // available: "1.0.5"

  const val android_image_cropper: String = "2.8.0"

  const val tooltips: String = "1.0.6" // available: "1.0.11"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val junit: String = "4.12"

  const val shortcutbadger: String = "1.1.16" // available: "1.10-WS1"

  const val time_duration_picker: String = "1.1.3"

  const val httpclient_android: String = "4.3.5" // available: "4.3.5.1"

  const val assertj_core: String = "3.11.1" // available: "3.13.2"

  const val conscrypt_android: String = "2.0.0" // available: "2.2.1"

  const val eventbus: String = "3.0.0"

  const val mockito_core: String = "1.9.5" // available: "3.0.0"

  const val org_powermock: String = "1.6.1" // available: "1.7.4"

  const val org_robolectric: String = "4.2" // available: "4.3"

  const val aesgcmprovider: String = "0.0.3"

  const val android_database_sqlcipher: String = "3.5.9-S3"

  const val signal_service_android: String = "2.13.7"

  const val webrtc_android: String = "M75" // available: "14579"

  const val waitingdots: String = "0.1.0" // available: "0.2.0"

  const val stickylistheaders: String = "2.7.0"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6"

  const val gradleCurrentVersion: String = "5.2.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
